### ISSUE TITLE
Libav is disabled because it unmaintained

### ISSUE THREAD

**Issue by mechamogeo** [membraneframework/membrane_h264_ffmpeg_plugin#77]
So i create a issue at membraneframework/membrane_demo#230 of becoming this plugin usage, the repo demonstration named as `rtp_to_hls` use this plugin, but in MacBook it's unacessible for me compile using the Xcode tools, I also tried but i  have no success with.

The errors occurs into usage of `libavcodec` and `libavutil` as mentioned before in another issue repo!

**Comment by bblaszkow06** [comment]
Hey @mechamogeo, sorry for missing this issue and the late response. The problem is that you're using the wrong library. Libav is indeed unmaintained, but it was a fork of FFmpeg.
You should install the FFmpeg binary that provides the mentioned `libavcodec` and `libavutil` libs using the instructions from [README](https://github.com/membraneframework/membrane_h264_ffmpeg_plugin#macos)
